strategy: multi_asset_rsi
script_file: "../scripts/multi_asset_rsi.py"

markets:
  binance:
    - BTC-USDT
    - ETH-USDT

params:
  # 策略参数
  trading_pairs: ["BTC-USDT", "ETH-USDT"]
  exchange: "binance"
  rsi_length: 14
  eth_btc_rsi_length: 14
  bullish_rsi_entry: 70
  bullish_rsi_exit: 65
  bearish_rsi_entry: 30
  bearish_rsi_exit: 35
  sma_length: 200
  allocation: 0.98
  rebalance_threshold: 0.1
  max_position_ratio: 0.25
  stop_loss_pct: 0.20
  trailing_stop_activation: 0.05
  trailing_delta: 0.03

# 资金分配（示例）
portfolio:
  binance:
    USDT: 10000
    BTC: 0
    ETH: 0
